# [SERVICE NAME]
service: backend
# [START runtime]
runtime: nodejs12
vpc_access_connector:
  name: projects/naroo-on-portfolio/locations/asia-northeast3/connectors/postgres-connector
# [END runtime]
