# [SERVICE NAME]
service: naroo-on-backend
# [START runtime]
runtime: nodejs18
vpc_access_connector:
  name: projects/my-pro48128ject-48128/locations/asia-northeast3/connectors/sql-connector
# [END runtime]
